// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtxqynbqwlxhamdiwqfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0eHF5bmJxd2x4aGFtZGl3cWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzQxMjYsImV4cCI6MjA2NzgxMDEyNn0.8VzwvVr78eztVIsP38lF8_mf_s1511-9RMZzoU9labI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});