// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqoxyqpecbmikbhisivu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxb3h5cXBlY2JtaWtiaGlzaXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzU5MTMsImV4cCI6MjA2NzgxMTkxM30.LmQkivfKMBN5e6nt53GvDL_TkUGhQqGCAqWf8ikhS9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});